#!/usr/bin/env python3
"""Build a deterministic, SDK-free Debian Web package using only Python.

This can assemble an architecture-all package on a development workstation.
Installation/runtime qualification still runs in Debian 13; assembly is not
reported as a successful target-system test.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import json
import os
from pathlib import Path
import re
import tarfile

ROOT = Path(__file__).resolve().parents[1]


def tar_bytes(files, epoch):
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w", format=tarfile.USTAR_FORMAT) as tar:
        directories = {str(parent) for name in files for parent in Path(name).parents if str(parent) != "."}
        for directory in sorted(directories):
            info = tarfile.TarInfo("./" + directory)
            info.type, info.mode, info.mtime = tarfile.DIRTYPE, 0o755, epoch
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            tar.addfile(info)
        for name, (content, mode) in sorted(files.items()):
            info = tarfile.TarInfo("./" + name)
            info.mode, info.mtime, info.size = mode, epoch, len(content)
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            tar.addfile(info, io.BytesIO(content))
    return gzip.compress(buffer.getvalue(), compresslevel=9, mtime=0)


def ar_bytes(members, epoch):
    data = bytearray(b"!<arch>\n")
    for name, content in members:
        header = f"{name + '/':<16}{epoch:<12}{0:<6}{0:<6}{'100644':<8}{len(content):<10}`\n"
        if len(header) != 60:
            raise ValueError("invalid ar header")
        data.extend(header.encode("ascii"))
        data.extend(content)
        if len(content) % 2:
            data.extend(b"\n")
    return bytes(data)


def build(root: Path, output: Path, version: str, epoch: int):
    if not re.fullmatch(r"[0-9][0-9A-Za-z.+:~\-]*", version):
        raise ValueError("invalid Debian version")
    if not (root / "frontend/dist/index.html").is_file():
        raise ValueError("frontend production build is missing; run npm --prefix frontend run build")
    documents = json.loads((root / "deploy/public-documents.json").read_text())
    if (not isinstance(documents, list) or not documents
            or any(not isinstance(name, str) or not re.fullmatch(r"[A-Z0-9_-]+\.md", name) for name in documents)
            or len(set(documents)) != len(documents)):
        raise ValueError("invalid public document allowlist")
    files = {}
    def add(source, destination, mode=0o644):
        files[destination] = ((root / source).read_bytes(), mode)
    for source in sorted((root / "backend/fm10k_controlpanel").glob("*.py")):
        add(source.relative_to(root), f"usr/lib/fm10k-controlpanel/python/fm10k_controlpanel/{source.name}")
    files["usr/lib/fm10k-controlpanel/python/fm10k_controlpanel/_package_version.py"] = (
        f"# Generated by the Debian package builder.\nPACKAGE_VERSION = {version!r}\n".encode(), 0o644)
    for source in sorted((root / "frontend/dist").rglob("*")):
        if source.is_file() and source.name != ".DS_Store" and not source.name.startswith("._"):
            add(source.relative_to(root), "usr/share/fm10k-controlpanel/web/" + str(source.relative_to(root / "frontend/dist")))
    add("deploy/entry.py", "usr/lib/fm10k-controlpanel/entry.py")
    add("deploy/systemd/fm10k-panel.service", "usr/lib/systemd/system/fm10k-panel.service")
    for unit in ("fm10k-time.socket", "fm10k-time@.service", "fm10k-update.socket", "fm10k-update@.service", "fm10k-update-worker.service"):
        add("deploy/systemd/" + unit, "usr/lib/systemd/system/" + unit)
    add("deploy/panel.env", "etc/fm10k-controlpanel/panel.env")
    add("deploy/nginx/fm10k-controlpanel.conf.in", "usr/share/fm10k-controlpanel/nginx.conf.in")
    add("hardware/sdk-inputs.json", "usr/share/fm10k-controlpanel/sdk-inputs.json")
    add("vendor/netlab/NOTICE", "usr/share/doc/fm10k-controlpanel/NETLAB-NOTICE")
    add("vendor/netlab/LICENSE", "usr/share/doc/fm10k-controlpanel/NETLAB-LICENSE")
    add("LICENSE", "usr/share/doc/fm10k-controlpanel/LICENSE")
    add("NOTICE", "usr/share/doc/fm10k-controlpanel/NOTICE")
    for name in documents:
        add("docs/" + name, "usr/share/doc/fm10k-controlpanel/" + name)
    # Only the authenticated Python IPC transport, not SDK/vendor daemons.
    for source in ("bin/cli/session.py", "scripts/netlab_ipc_transport.py"):
        add("vendor/netlab/" + source, "usr/lib/fm10k-controlpanel/netlab/" + source)
    for name, subcommand in (("fm10k-panel", "web"), ("fm10k-preflight", "preflight"), ("fm10k-https", "https")):
        files["usr/bin/" + name] = (f'#!/bin/sh\nexec /usr/bin/python3 -I /usr/lib/fm10k-controlpanel/entry.py {subcommand} "$@"\n'.encode(), 0o755)
    control = f"""Package: fm10k-controlpanel
Version: {version}
Architecture: all
Maintainer: AAA404 <AAA404@users.noreply.github.com>
Section: admin
Priority: optional
Depends: python3 (>= 3.13), python3 (<< 3.14), python3-fastapi (>= 0.115), python3-pydantic (>= 2.10), python3-uvicorn (>= 0.32), adduser, init-system-helpers, systemd
Recommends: nginx, openssl, systemd-timesyncd
Description: FM10840 Debian 13 Web management and simulator
 Native hardware operations require the separately built NetLab board adapter.
 The default service listens only on loopback and uses simulated hardware.
"""
    controls = {"control": (control.encode(), 0o644),
                "conffiles": (b"/etc/fm10k-controlpanel/panel.env\n", 0o644)}
    for name in ("postinst", "prerm", "postrm"):
        controls[name] = ((root / "deploy/debian" / name).read_bytes(), 0o755)
    controls["md5sums"] = ("".join(f"{hashlib.md5(data, usedforsecurity=False).hexdigest()}  {name}\n"
                                   for name, (data, _) in sorted(files.items())).encode(), 0o644)
    output.parent.mkdir(parents=True, exist_ok=True)
    data = ar_bytes([("debian-binary", b"2.0\n"), ("control.tar.gz", tar_bytes(controls, epoch)),
                     ("data.tar.gz", tar_bytes(files, epoch))], epoch)
    output.write_bytes(data)
    report = {"package": output.name, "version": version, "architecture": "all", "target": "Debian 13",
              "sha256": hashlib.sha256(data).hexdigest(), "source_date_epoch": epoch,
              "contains_sdk": False, "contains_native_hal": False,
              "qualification": "assembled; Debian installation and native hardware validation are separate"}
    output.with_suffix(".manifest.json").write_text(json.dumps(report, indent=2) + "\n")
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default=(ROOT / "VERSION").read_text().strip())
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    output = args.output or ROOT / "artifacts" / f"fm10k-controlpanel_{args.version}_all.deb"
    print(json.dumps(build(ROOT, output, args.version, int(os.environ.get("SOURCE_DATE_EPOCH", "0"))), indent=2))


if __name__ == "__main__":
    main()
