/* Shared-fixture checks for the resizable inspector; never contacts a device. */
const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const path = require('node:path')

module.exports = async function checkPortInspector(page, output, writes) {
  const detail=page.locator('#port-details-0'), dialog=page.locator('.port-inspector-dialog[open]')
  const beforeWrites=[...writes], layouts=[]
  const geometry=()=>page.evaluate(()=>{
    const origin=document.querySelector('.port-groups-view').getBoundingClientRect()
    return [...document.querySelectorAll('.epl-box')].map(el=>{const b=el.getBoundingClientRect();return [b.x-origin.x,b.y-origin.y,b.width,b.height]})
  })
  const measure=()=>dialog.evaluate(async el=>{
    await new Promise(requestAnimationFrame)
    const b=el.getBoundingClientRect(),body=el.querySelector('.port-detail-body')
    return {viewport:[innerWidth,innerHeight],width:b.width,height:b.height,bodyHeight:body.clientHeight,
      inside:b.left>=-1&&b.top>=-1&&b.right<=innerWidth+1&&b.bottom<=innerHeight+1,
      overflow:document.documentElement.scrollWidth>innerWidth||el.scrollWidth>el.clientWidth+1||body.scrollWidth>body.clientWidth+1,
      fontSize:parseFloat(getComputedStyle(body).fontSize)}
  })
  await detail.getByRole('tab',{name:'端口详情',exact:true}).click()
  await detail.getByRole('button',{name:'查看 P1 采样说明',exact:true}).click()
  await detail.locator('.port-detail-body').evaluate(el=>el.scrollTop=1000)
  const scroll=await detail.locator('.port-detail-body').evaluate(el=>el.scrollTop)
  assert(scroll>0,'the compact inspector has a scroll position to preserve')
  const before=await geometry(),element=await detail.elementHandle()
  await detail.getByRole('button',{name:'放大端口详情',exact:true}).click()
  await dialog.waitFor()
  const opened=await measure()
  assert(Math.abs(opened.width-1100)<1&&opened.bodyHeight>=500&&opened.fontSize>=13,JSON.stringify(opened))
  assert(opened.inside&&!opened.overflow)
  assert(await element.evaluate(el=>el===document.querySelector('.port-inspector-dialog #port-details-0')),'enlarging moves the existing content')
  const background=await geometry()
  before.forEach((rect,i)=>rect.forEach((value,j)=>assert(Math.abs(value-background[i][j])<1,'enlarging must not move or resize an EPL')))
  await dialog.screenshot({path:path.join(output,'inspector-p1-desktop.png')})
  const handle=dialog.getByRole('button',{name:'调整端口详情窗口大小，方向键调整',exact:true})
  const grip=await handle.boundingBox()
  await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2)
  await page.mouse.down();await page.mouse.move(grip.x+grip.width/2-70,grip.y+grip.height/2-60,{steps:5});await page.mouse.up()
  const dragged=await measure()
  assert(dragged.width<opened.width-80&&dragged.height<opened.height-80&&dragged.inside,'pointer resizing changes the real layout')
  await handle.focus();await page.keyboard.press('ArrowRight')
  const resized=await measure();assert.equal(resized.width,dragged.width+20)
  await dialog.getByRole('button',{name:'最大化端口详情',exact:true}).click()
  const maximized=await measure()
  assert(maximized.width>resized.width&&maximized.height>resized.height&&maximized.inside)
  await dialog.getByRole('button',{name:'还原窗口大小',exact:true}).click()
  assert.equal((await measure()).width,resized.width)
  assert.equal((await measure()).height,resized.height)
  await dialog.getByRole('button',{name:'回到卡片',exact:true}).click()
  await dialog.waitFor({state:'hidden'})
  assert.equal(await detail.locator('.port-detail-body').evaluate(el=>el.scrollTop),scroll)
  assert(await page.locator('#port-detail-expand-1').evaluate(el=>el===document.activeElement),'return restores focus to the expand action')
  assert.equal(await page.evaluate(()=>document.documentElement.style.overflow),'')
  assert.deepEqual(await geometry(),before)
  await detail.getByRole('button',{name:'查看 P1 采样说明',exact:true}).click()

  // An unconfirmed rate choice survives moving the inspector; Escape cancels only that edit.
  await detail.getByRole('button',{name:'调整 P1 速率',exact:true}).click()
  const speed=detail.getByRole('combobox',{name:'P1 端口速率',exact:true})
  await speed.selectOption('10')
  await detail.getByRole('button',{name:'放大端口详情',exact:true}).click()
  assert.equal(await speed.inputValue(),'10')
  await dialog.getByRole('button',{name:'最大化端口详情',exact:true}).click()
  assert.equal(await speed.inputValue(),'10')
  await speed.focus();await page.keyboard.press('Escape')
  await speed.waitFor({state:'detached'});assert(await dialog.isVisible())
  await dialog.getByRole('button',{name:'还原窗口大小',exact:true}).click()
  await dialog.getByRole('button',{name:'调整 P1 速率',exact:true}).click()
  await speed.selectOption('10')
  await dialog.getByRole('button',{name:'暂存',exact:true}).click()
  assert.equal(await page.locator('#port-tile-1 .port-tile-speed').innerText(),'10G')
  await dialog.getByRole('button',{name:'设置端口 P1',exact:true}).click()
  const settings=page.locator('.port-settings-modal[open]')
  await settings.waitFor();assert.equal(await settings.getByLabel('P1 / Lane 0').inputValue(),'10')
  await page.keyboard.press('Escape');await settings.waitFor({state:'hidden'})
  assert(await dialog.isVisible(),'Escape in settings must leave the inspector open')
  assert(await dialog.locator('.port-inspector-settings').evaluate(el=>el===document.activeElement))
  await dialog.getByRole('tab',{name:'收发统计',exact:true}).click()
  await dialog.getByRole('combobox',{name:'切换详情端口',exact:true}).selectOption('2')
  await dialog.getByRole('heading',{name:'P2 · 端口详情',exact:true}).waitFor()
  assert.equal(await dialog.getByRole('tab',{name:'收发统计',exact:true}).getAttribute('aria-selected'),'true')
  await dialog.getByRole('combobox',{name:'切换详情端口',exact:true}).selectOption('1')
  await dialog.getByRole('heading',{name:'P1 · 端口详情',exact:true}).waitFor()
  await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'})
  assert.equal(await page.locator('#port-tile-1').getAttribute('aria-expanded'),'true')
  assert.equal(await detail.getByRole('tab',{name:'收发统计',exact:true}).getAttribute('aria-selected'),'true')
  await page.locator('.save-bar').getByRole('button',{name:'丢弃修改',exact:true}).click()
  await page.locator('.save-bar').waitFor({state:'detached'})
  assert.equal(await page.locator('#port-tile-1 .port-tile-speed').innerText(),'25G')
  await detail.getByRole('button',{name:'放大端口详情',exact:true}).click()
  for(const viewport of [{width:1280,height:720},{width:761,height:650},{width:700,height:700},{width:390,height:844},{width:320,height:640},{width:1440,height:1080}]){
    await page.setViewportSize(viewport)
    const metrics=await measure();layouts.push(metrics)
    assert(metrics.inside&&!metrics.overflow&&metrics.bodyHeight>=180,JSON.stringify(metrics))
    if(viewport.width<=700){
      assert(Math.abs(metrics.width-viewport.width)<1&&Math.abs(metrics.height-viewport.height)<1,'narrow inspectors fill the viewport')
      assert.equal(await dialog.locator('.port-inspector-resize').count(),0)
    }
    if([320,390].includes(viewport.width))await dialog.screenshot({path:path.join(output,'inspector-p1-'+viewport.width+'.png')})
  }
  await dialog.getByRole('button',{name:'回到卡片',exact:true}).click()
  await detail.getByRole('tab',{name:'端口详情',exact:true}).click()
  assert.deepEqual(writes,beforeWrites,'resizing, settings drafts and port selection must not write to the device')
  await fs.writeFile(path.join(output,'inspector-report.json'),JSON.stringify({passed:true,opened,dragged,maximized,layouts,hardware_writes:0},null,2)+'\n')
}
