/* Isolated browser regression. Real Python preflight; no live board access. */
const {chromium} = require(process.env.FM10K_PLAYWRIGHT_MODULE || '../frontend/node_modules/playwright')
const {spawnSync} = require('node:child_process')
const fs = require('node:fs/promises'), path = require('node:path'), assert = require('node:assert/strict')
;(async()=>{
  const root=path.resolve(__dirname,'..'), base='http://127.0.0.1:18129'
  function python(code, input) {
    const r=spawnSync(process.env.FM10K_PYTHON || 'python3',['-c',code],{cwd:root,env:{...process.env,PYTHONPATH:path.join(root,'backend')},input:JSON.stringify(input),encoding:'utf8'})
    assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout)
  }
  const configuration=python('from fm10k_controlpanel.models import SwitchConfiguration; print(SwitchConfiguration().model_dump_json())')
  configuration.groups.forEach(g=>g.mode='40g')
  configuration.vlans.push({id:10,name:'RDMA'})
  const capabilities=python('import json; from fm10k_controlpanel.roce import capabilities; print(json.dumps(capabilities()))')
  const errors=[], integration={'startup-mode':'control','board-hal':'bound',synchronized:'true'}
  let failure=false, stale=false, simulated=false, proposal, previews=0
  let deviceOffset=-86400, includeServerTime=true, readRevision=64, appliedMatch=true, reads=0
  const browser=await chromium.launch({headless:true,...(process.env.FM10K_BROWSER_CHANNEL ? {channel:process.env.FM10K_BROWSER_CHANNEL} : {})})
  const deadline=setTimeout(()=>{console.error('RoCE browser regression exceeded 120 seconds');process.exitCode=1;void browser.close()},120000)
  const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'zh-CN',acceptDownloads:true})
  page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000)
  try {
    await page.route('**/*',async route=>{
      const req=route.request(),url=new URL(req.url());assert.equal(url.origin,base)
      const send=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)})
      switch(url.pathname){
        case '/api/v1/auth/session': return send({initialized:true,authenticated:true,username:'fixture',csrf:'fixture',mode:'netlab'})
        case '/api/v1/capabilities': return send({mode:'netlab',native_integration:integration,roce:capabilities})
        case '/api/v1/config': return send({configuration,revision:64,pending:null})
        case '/api/v1/updates': return send({enabled:false,state:'reserved'})
        case '/api/v1/telemetry': return send({native_integration:integration,control_available:true,ports:[],sensors:{temperatures:[],fan:{}},optics:[]})
        case '/api/v1/roce/preflight':
          assert.equal(req.headers()['x-csrf-token'],'fixture')
          return send(python('import sys,json; from fm10k_controlpanel.roce import preflight; print(json.dumps(preflight(json.load(sys.stdin))))',req.postDataJSON().configuration))
        case '/api/v1/operational/roce': {
          reads++
          const serverTime=Date.now()/1000+deviceOffset
          return failure ? send({detail:'fixture: readback unavailable'},503) : send({mode:'netlab',...(includeServerTime ? {server_time:serverTime} : {}),data:{revision:readRevision,quality:simulated?'simulated':'valid',enabled:false,buffer_ready:true,configuration_applied:appliedMatch,traffic_validation:'not-run',sampled_at:serverTime-(stale?60:0),tc_smp_map:Array(8).fill('smp-0'),ports:[{port:13,selected:false,quality:'valid',link:'down',counters:{rx_pfc_packets:0,tx_pfc_packets:10,rx_congestion_drops:null,tx_congestion_drops:0},tc3_usage_bytes:null}]}})
        }
        case '/api/v1/config/preview':
          previews++; proposal=req.postDataJSON()
          const result=python('import sys,json; from fm10k_controlpanel.roce import preflight; print(json.dumps(preflight(json.load(sys.stdin))))',proposal.configuration)
          assert(result.valid,JSON.stringify(result.issues))
          return send({id:'fixture-draft',configuration:proposal.configuration,changes:[{label:'RoCE · 启用',path:'/qos/roce/enabled',before:false,after:true}],affected_epls:[0,1,2,5,6,7],global_qos_change:true,group_changes:[],requires_bandwidth_ack:false,bandwidth:{}})
      }
      assert(!url.pathname.startsWith('/api/'),url.pathname)
      const name=url.pathname==='/'?'index.html':url.pathname.slice(1)
      return route.fulfill({contentType:name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html',body:await fs.readFile(path.join(root,'frontend/dist',name))})
    })
    await page.goto(base)
    await page.getByRole('button',{name:'二层交换',exact:true}).click()
    await page.getByRole('tab',{name:'RDMA / RoCE',exact:true}).click()
    assert.deepEqual(capabilities.qualifications,[])
    await page.getByText('需独立验收',{exact:true}).waitFor()
    assert.equal(await page.locator('.roce-results').count(),0)
    await page.getByText('已关闭',{exact:true}).waitFor()
    const firstReads=reads
    console.log('PASS: refreshed state with device clock one day behind')
    await page.waitForTimeout(11000)
    await page.getByText('已关闭',{exact:true}).waitFor()
    assert(reads>firstReads,'visible RoCE page must refresh automatically')
    deviceOffset=86400
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('已关闭',{exact:true}).waitFor()
    includeServerTime=false
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('等待有效回读',{exact:true}).waitFor()
    includeServerTime=true;readRevision=63
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('等待有效回读',{exact:true}).waitFor()
    readRevision=64;appliedMatch=false
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('配置不一致',{exact:true}).waitFor()
    appliedMatch=true
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('已关闭',{exact:true}).waitFor()
    await page.getByRole('button',{name:'设备概览',exact:true}).click()
    const inactiveReads=reads
    await page.waitForTimeout(11000)
    assert.equal(reads,inactiveReads,'leaving L2 must stop RoCE polling')
    console.log('PASS: auto refresh, clock ahead, invalid readback, inactive page')
    await page.getByRole('button',{name:'二层交换',exact:true}).click()
    await page.getByText('已关闭',{exact:true}).waitFor()
    await page.getByRole('button',{name:'配置 RoCE',exact:true}).click()
    await page.getByRole('button',{name:'下一步',exact:true}).click()
    await page.getByLabel('选择 P13',{exact:true}).check()
    await page.getByLabel('选择 P17',{exact:true}).check()
    assert(await page.getByLabel('选择 P14',{exact:true}).isDisabled())
    await page.getByRole('button',{name:'取消引导',exact:true}).click()
    assert.equal(await page.getByLabel('启用静态 PFC RoCE').isChecked(),false)
    assert.equal(await page.getByLabel('选择 P13',{exact:true}).isChecked(),false)
    assert.equal(previews,0)
    console.log('PASS: wizard cancellation')
    await page.getByRole('button',{name:'重新运行引导',exact:true}).click()
    await page.getByRole('button',{name:'下一步',exact:true}).click()
    await page.getByLabel('选择 P13',{exact:true}).check()
    await page.getByLabel('选择 P17',{exact:true}).check()
    await page.getByRole('button',{name:'下一步',exact:true}).click()
    await page.getByText('RoCE 参与端口必须具有共同的带标签 VLAN',{exact:true}).waitFor()
    assert(await page.getByRole('button',{name:'下一步',exact:true}).isDisabled())
    await page.getByLabel('加入现有业务 VLAN').selectOption('10')
    await page.getByRole('button',{name:'为所选端口加入 Tagged VLAN',exact:true}).click()
    await page.getByLabel('启用 P13（false → true）',{exact:true}).check()
    await page.getByLabel('启用 P17（false → true）',{exact:true}).check()
    await page.getByRole('button',{name:'加入所选建议修改',exact:true}).click()
    await page.getByText('软件预检通过；提交前仍需原生校验与差异确认。',{exact:true}).waitFor()
    await page.getByText('高级参数与缓冲预算',{exact:true}).click()
    await page.getByLabel('对端暂停响应上限（纳秒）').fill('10000')
    await page.getByText('RoCE P13 暂停响应预算超出已配置 headroom',{exact:true}).waitFor()
    assert(await page.getByRole('button',{name:'下一步',exact:true}).isDisabled())
    await page.getByLabel('对端暂停响应上限（纳秒）').fill('3000')
    await page.getByLabel('启用 PFC watchdog',{exact:true}).check()
    await page.getByLabel('停滞检测时间（毫秒）',{exact:true}).fill('40000')
    await page.getByText(/PFC watchdog 冷却时间不能小于检测时间/).waitFor()
    await page.getByLabel('停滞检测时间（毫秒）',{exact:true}).fill('5000')
    await page.getByText('软件预检通过；提交前仍需原生校验与差异确认。',{exact:true}).waitFor()
    await fs.mkdir(path.join(root,'artifacts/roce-ui'),{recursive:true})
    await page.screenshot({path:path.join(root,'artifacts/roce-ui/wizard-desktop.png'),fullPage:true})
    await page.getByRole('button',{name:'下一步',exact:true}).click()
    await page.getByRole('button',{name:'预览变更',exact:true}).click()
    await page.getByRole('dialog',{name:'检查配置变更'}).waitFor()
    assert.equal(proposal.configuration.qos.roce.enabled,true)
    assert.deepEqual(proposal.configuration.qos.roce.watchdog,{enabled:true,detect_ms:5000,recovery_ms:100,cooldown_ms:30000})
    assert.deepEqual(proposal.configuration.qos.roce.ports,[13,17])
    assert.deepEqual(proposal.configuration.ports['13'].tagged_vlans,[10])
    assert.equal(proposal.configuration.ports['13'].mtu,configuration.ports['13'].mtu)
    assert.equal(proposal.configuration.ports['13'].pvid,configuration.ports['13'].pvid)
    await page.getByText('速率、MTU、优先级或 PFC 变更会重算全芯片缓冲水位，事务协调范围为全部 EPL。',{exact:true}).waitFor()
    await page.getByRole('button',{name:'返回编辑',exact:true}).click()
    await page.getByText('待应用',{exact:true}).waitFor()
    await page.getByRole('button',{name:'诊断',exact:true}).click()
    assert(await page.getByRole('cell',{name:'不可用',exact:true}).count()>=2)
    assert(await page.getByRole('cell',{name:'0',exact:true}).count()>=1)
    const downloaded=page.waitForEvent('download')
    console.log('PASS: real preflight and preview; checking diagnostic export')
    await page.getByRole('button',{name:'导出诊断 JSON',exact:true}).click()
    const download=await downloaded
    const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'))
    assert.equal(exported.revision,64);assert.equal(exported.operational.traffic_validation,'not-run')
    assert.deepEqual(exported.qualification_records,[])
    stale=true
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('未知 / 样本过期',{exact:true}).waitFor()
    stale=false;simulated=true
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('模拟 · 无硬件证明',{exact:true}).waitFor()
    failure=true
    await page.getByRole('button',{name:'刷新硬件状态',exact:true}).click()
    await page.getByText('硬件状态读取失败，请重试。当前没有可用于确认配置的读数。',{exact:true}).waitFor()
    assert.equal(await page.getByRole('cell',{name:'10',exact:true}).count(),0)
    failure=false;simulated=false
    await page.waitForTimeout(11000)
    await page.getByText('未启用',{exact:true}).waitFor()
    await page.setViewportSize({width:390,height:844})
    await page.waitForTimeout(350)
    assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth))
    await page.screenshot({path:path.join(root,'artifacts/roce-ui/diagnostics-mobile.png'),fullPage:true})
    await page.getByRole('button',{name:'配置',exact:true}).click()
    await page.getByLabel('流量分类',{exact:true}).selectOption('dscp')
    await page.getByLabel('DCBX 策略交换',{exact:true}).selectOption('ieee')
    await page.getByLabel('CNP DSCP',{exact:true}).fill('26')
    await page.getByText(/RoCE 数据与 CNP 必须使用不同的 DSCP/).waitFor()
    await page.getByLabel('CNP DSCP',{exact:true}).fill('48')
    await page.getByRole('checkbox',{name:/保留数据优先级 3 → TC3、CNP 优先级 6 → TC7/}).check()
    await page.getByRole('button',{name:'加入所选建议修改',exact:true}).click()
    await page.getByText('软件预检通过；提交前仍需原生校验与差异确认。',{exact:true}).waitFor()
    await page.getByRole('button',{name:'预览 RoCE 变更',exact:true}).click()
    await page.getByRole('dialog',{name:'检查配置变更'}).waitFor()
    assert.equal(proposal.configuration.qos.roce.classification,'dscp')
    assert.equal(proposal.configuration.qos.roce.dcbx,'ieee')
    assert.equal(proposal.configuration.qos.roce.dscp,26)
    assert.equal(proposal.configuration.qos.roce.cnp_dscp,48)
    assert.deepEqual(proposal.configuration.qos.priority_map.slice(6),[7,6])
    await page.getByRole('button',{name:'返回编辑',exact:true}).click()
    await page.getByLabel('启用静态 PFC RoCE').uncheck()
    await page.getByText('软件预检通过；提交前仍需原生校验与差异确认。',{exact:true}).waitFor()
    await page.getByRole('button',{name:'预览 RoCE 变更',exact:true}).click()
    await page.getByRole('dialog',{name:'检查配置变更'}).waitFor()
    assert.equal(proposal.configuration.qos.roce.enabled,false)
    assert.deepEqual(proposal.configuration.ports['13'].tagged_vlans,[10])
    assert.deepEqual(errors,[])
    console.log('PASS: clock skew both ways, automatic refresh/recovery, page exit, missing clock/revision mismatch, empty qualification records, wizard, real preflight, preview, stale/simulated/error data, export, responsive UI')
  } finally {clearTimeout(deadline);await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1})
